### PR TITLE
feat: custom format parser project #708

### PR DESCRIPTION
**Pull request by galihlprakoso**
This pull request addresses the following issue: [firebase/genkit#708](https://github.com/firebase/genkit/issues/708).

The changes introduce a new abstraction, `FormatParser`, which aims to replace the existing behavior of the `output()` method in Genkit results. As noted by @mbleigh:

> "Currently, the `output()` method on Genkit results attempts to leniently parse JSON based on whether a format is supplied or an output schema is present. However, there are various reasons why someone might need greater control over output parsing."

The new `FormatParser` abstraction provides a more flexible and customizable approach to parsing output, enabling users to manage output formatting according to their specific requirements.

---

Let me know if you need further adjustments or additional details!

Checklist (if applicable):
- [x] Unit Tested
- [ ] Manually Tested
- [ ] Docs updated

### CODE REVIEW

**Comment by pavelgj** [comment]
Thanks for the pull request! I'll let @mbleigh and @ifielker comment on the specifics of this feature, but a more general comment:  we are currently not accepting new features on the `main` branch. Our next major release if getting close and all new feature work is currently done on the `next` branch. I realize it's probably a lot of work, but could you please rebase this PR on the `next` branch?

**Comment by galihlprakoso** [comment]
> Thanks for the pull request! I'll let @mbleigh and @ifielker comment on the specifics of this feature, but a more general comment:  we are currently not accepting new features on the `main` branch. Our next major release if getting close and all new feature work is currently done on the `next` branch. I realize it's probably a lot of work, but could you please rebase this PR on the `next` branch?

Thank you! Sure! So I just rebase this PR on the next branch and draft my PR there? @pavelgj

**Comment by mbleigh** [comment]
Thank you for the contribution! I've been thinking about this more and have some tweaks to the API and behavior in mind. Before you reimplement on Next, can you give me a couple days to fully flesh out the proposal I'd like to go with?

**Comment by galihlprakoso** [comment]
> Thank you for the contribution! I've been thinking about this more and have some tweaks to the API and behavior in mind. Before you reimplement on Next, can you give me a couple days to fully flesh out the proposal I'd like to go with?

Sure! Thanks! I'll just close this PR for now then. @mbleigh

**Pull request closed without merging**
