### PR TITLE
Set span type to prompt when rendering a dotprompt

### PR DESCRIPTION
**Pull request by MichaelDoyle**
This will enable the Dev UI to properly deal with prompts in a more generic way when rendering badges, loading traces into the runner, etc, versus having to check for each different type of prompt ['prompt', 'DOTprompt', 'FOOprompt'] etc.

image

Checklist (if applicable):
- [x] Tested (manually, unit tested, etc.)

### CODE REVIEW

**Comment by MichaelDoyle** [comment]
cc @tonybaroneee this will be relevant for the firebase console as well.

**Review by tonybaroneee — APPROVED** [review]

**Comment by MichaelDoyle** [comment]
On second thought, this doesn't look to be _exactly_ what we want.

I think we want

```
type: 'action'
subtype: 'prompt'
```

**Comment by maxl0rd** [comment]
I think this is on the right track, but I have a counter proposal since this is colliding with the feature tracing change.

**Review by tonybaroneee — CHANGES_REQUESTED** [review]
(See Max's comment)

**Pull request closed without merging**
