### PR TITLE
[JS] feat: Qdrant Plugin

### PR DESCRIPTION
**Pull request by Anush008**
## Description

Hello guys. Greetings from Qdrant 👋.

This PR adds a `genkitx-qdrant` plugin to support retrieval and indexing using Qdrant - https://qdrant.tech.

Checklist (if applicable):
- [x] Tested
- [x] Example app
- [x] Docs

### CODE REVIEW

**Comment by i14h** [comment]
Hi @Anush008, 
Excited to see your cool plugin! As outlined [here](https://firebase.google.com/docs/genkit/plugin-authoring#publishing_a_plugin) you publish your plugin as an npm plugin yourself. This directory is reserved for plugins built by the Genkit team. You can publish directly from your own repo under `genkitx-*` package and it'll be available to everyone right away.

**Comment by Anush008** [comment]
Hi @i14h. Thanks for letting me know. Will move to a separate repo. Can we have  the plugin listed and it's docs?

**Comment by Anush008** [comment]
Hey @i14h, just bumping https://github.com/firebase/genkit/pull/270#issuecomment-2139236516 since it's been a while. Please let us know when possible.

**Comment by apascal07** [comment]
@Anush008 We won't be listing specific 3rd party plugins in the docs but in the future, we will link to the NPM registry where they can all be found here: https://firebase.google.com/docs/genkit/plugin-authoring#publishing_a_plugin

**Comment by Anush008** [comment]
Got it. Also, we've built a Go plugin for Qdrant. Will make it available once Go support is public.
Please let us know if there are any developments related to it.

**Comment by Anush008** [comment]
Hey guys. Thanks for your time.
We have the JS and Go plugin at https://github.com/qdrant/qdrant-genkit.

**Pull request closed without merging**
