### PR TITLE
Add Gemini 1.5 Pro Flash

### PR DESCRIPTION
**Pull request by MichaelDoyle**
image

### CODE REVIEW

**Review by pavelgj — APPROVED** [review]

**Comment by pavelgj** [comment]
wait

**Comment by pavelgj** [comment]
need to export flag model from the plugin index.ts

**Comment by mbleigh** [comment]
I can haz vertex too?

**Review by pavelgj — CHANGES_REQUESTED** [review]
export `gemini15Flash` model from the index.ts

**Review by pavelgj — APPROVED** [review]

**Pull request merged**
