### PR TITLE
Update pgvector docs to include Go (using weave)

### PR DESCRIPTION
**Pull request by ssbushi**
Checklist (if applicable):
- [x] Docs updated

### CODE REVIEW

**Comment by ssbushi** [comment]
I want to include more than just the code for defining a retriever (eg: the right imports). But using `%include` consecutively generates multiple code blocks in the markdown file. I opted to keep  it simple

**Review by kevinthecheung — CHANGES_REQUESTED** [review]
This won't render correctly with markdown embedded within the HTML. Could you please put these files in `docs-go` instead? (Just the go version.) I will combine everything all at once when go graduates out of alpha

**Review by jba — APPROVED** [review]

**Comment by ssbushi** [comment]
@kevinthecheung Moved the go snippets to `docs-go`. PTAL

**Review by kevinthecheung — APPROVED** [review]
Thank you!

**Pull request merged**
